version: '2'
services:

  database:
      image: mysql:5.5
      container_name: opencash_mysql
      restart: always
      ports :
       - 3306:3306
      environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=opencash
       - MYSQL_USER=opencash
       - MYSQL_PASSWORD=password
      volumes:
       - ./data:/var/lib/mysql
       - ./OpenCash-structure.sql:/docker-entrypoint-initdb.d/OpenCash-structure.sql

  opencash:
      build: .
      container_name: opencash_web
      restart: always
      ports :
       - 80:80
      environment:
       - MYSQL_HOST=database
       - MYSQL_PORT=3306
       - MYSQL_DATABASE=opencash
       - MYSQL_USER=opencash
       - MYSQL_PASSWORD=password
      volumes:
       - ./config:/usr/src/app/config
      links:
       - database