version: '2'
services:

  database:
      image: mysql:8.0.15
      container_name: opencash_mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=opencash
       - MYSQL_USER=opencash
       - MYSQL_PASSWORD=password
      volumes:
       - ./data:/var/lib/mysql
       - ./OpenCash-structure.sql:/docker-entrypoint-initdb.d/OpenCash-structure.sql

  opencash:
      build: .
      container_name: opencash_web
      ports :
       - 80:80
      environment:
       - MYSQL_HOST=database
       - MYSQL_PORT=3306
       - MYSQL_DATABASE=opencash
       - MYSQL_USER=opencash
       - MYSQL_PASSWORD=password
      volumes:
       - ./config:/usr/src/app/config
      links:
       - database